// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc9pErHtGMSJH6K7dGCTuXtQUrXbHL7KM',
    appId: '1:864068779012:web:6731c4a06365ac61914951',
    messagingSenderId: '864068779012',
    projectId: 'videoapp-9fc5e',
    authDomain: 'videoapp-9fc5e.firebaseapp.com',
    storageBucket: 'videoapp-9fc5e.appspot.com',
    measurementId: 'G-XY799QNS8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR5nm6L_dOhZE3Yi_TXHc2yUHQLxzTW1M',
    appId: '1:864068779012:android:63297979c3f03ee3914951',
    messagingSenderId: '864068779012',
    projectId: 'videoapp-9fc5e',
    storageBucket: 'videoapp-9fc5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsIJLwLG4C-46v-UZdmjEYk-xcnhjiRTw',
    appId: '1:864068779012:ios:95389f9144674a46914951',
    messagingSenderId: '864068779012',
    projectId: 'videoapp-9fc5e',
    storageBucket: 'videoapp-9fc5e.appspot.com',
    iosBundleId: 'com.example.clicks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsIJLwLG4C-46v-UZdmjEYk-xcnhjiRTw',
    appId: '1:864068779012:ios:465c4a8331ba24c9914951',
    messagingSenderId: '864068779012',
    projectId: 'videoapp-9fc5e',
    storageBucket: 'videoapp-9fc5e.appspot.com',
    iosBundleId: 'com.example.clicks.RunnerTests',
  );
}
